[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SPA routing so /bridal, /festival, /party load index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
